###지능형 리스트

In [1]:
#예제1
symbols = "$*&!@"
codes = []

for symbol in symbols:
    codes.append(ord(symbol))
#ord() 아스키코드를 정수로 표현해줌
print(codes)

[36, 42, 38, 33, 64]


In [2]:
#예제2
symbols = "$*&!@"

codes = [ord(symbol) for symbol in symbols]

print(codes)

[36, 42, 38, 33, 64]


In [3]:
#예제3
x = '"!$$*&!@'
dummy = [ord(x) for x in x]
#파이썬은 지역범위로 코드 블록을 구분하기 때문에
#지능형 리스트 내의 변수명이 같아도 실행 가능함.
print(x)
print(dummy)

"!$$*&!@
[34, 33, 36, 36, 42, 38, 33, 64]


In [18]:
#예제4
symbols = '"!~$$*&!@'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 32]
print(beyond_ascii)

[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [6]:
#예제5
symbols = '"!~$$*&!@'
beyond_ascii = list(filter(lambda c: c>64, map(ord,symbols)))
#filter() 값이 true인 경우만 값을 리턴
#lambda 일회용 함수 구현(원래는 def ~ 이런식으로 구현)
#map(매핑시킬 함수이름, 매핑 대상)
print(beyond_ascii, '\n')

print(f"Map function:\n>>> {map(ord,symbols)}")
print(f"List after map:\n>>> {list(map(ord,symbols))}")

[126] 

Map function:
>>> <map object at 0x7c5da468a6b0>
List after map:
>>> [34, 33, 126, 36, 36, 42, 38, 33, 64]


###데카르트 곱

In [8]:
#예제6
colors = ['black','white']
sizes = ['S','M','L']
tshirts = [(color, size) for color in colors for size in sizes]
#for size in sizes:
#   for colors in color:
#이런 조건문을 지능형리스트로 바꾸면 위의 문장이 됨.
print(tshirts)

for color in colors:
    for size in sizes:
      print((color, size))

[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


###제너레이터


In [9]:
#예제7
symbols = "!#^&&#"
ord_s = tuple(ord(s) for s in symbols if ord(s))
#지능형리스트는 시퀀스를 모두 실행하고 변수에 값을 반환하지만
#제너레이터는 파이프 라인을 만들어 내가 요청할 때마다 항목을 하나씩 처리해서 반환
#대용량 데이터 처리는 제너레이터가 유리.

#지능형 리스트(한번에 처리 후 반환)
#1,2,3,4,5  -> 1,2,3,4,5
#제너레이터(요청 시 마다 처리 후 반환)
#1->1, 2->2, 3->3, 4->4, 5->5
print(ord_s)

(33, 35, 94, 38, 38, 35)


In [10]:
#예제7
import array

ord_s = array.array('I', (ord(symbol) for symbol in symbols))
#값을 만들 때마다 array에 값 추가
#지능형 리스트라면 값을 모두 만든 후 추가
print(ord_s)

array('I', [33, 35, 94, 38, 38, 35])


In [11]:
#예제8
colors = ['black','white']
sizes = ['S','M','L']

for tshirt in ('{} {}'.format(c, s) for s in sizes for c in colors):
      print(tshirt)

black S
white S
black M
white M
black L
white L


###'레코드'로서의 튜플과 튜플 언패킹


In [14]:
#예제9
#레코드는 파일과 유사
#항목의 수가 고정되어 있고, 항목의 순서가 중요

lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'),
              ('BRA', 'CE342567'),
              ('ESP', 'XDA205856')]
#튜플 언패킹
for passport in sorted(traveler_ids):
    print('%s/%s' % passport)
    print('{}/{}'.format(passport[0], passport[1]))
    print(f'{passport[0]}/{passport[1]}')

BRA/CE342567
BRA/CE342567
BRA/CE342567
ESP/XDA205856
ESP/XDA205856
ESP/XDA205856
USA/31195855
USA/31195855
USA/31195855


In [16]:
#예제10
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'),
              ('BRA', 'CE342567'),
              ('ESP', 'XDA205856')]

for country, _ in traveler_ids:
    print(country)
#ex. USA가 country, 31195855가 _

USA
BRA
ESP


In [21]:
#예제11

lax_coordinates = (33.9425, -118.408056)
latitude, longtitude = lax_coordinates
print(latitude)
print(longtitude)

33.9425
-118.408056


In [19]:
#예제12
a=10; b=20
b, a = a,b
print(a, b)

20 10


In [20]:
#예제13
divmod(20,8)
#나누기 후 몪과 나머지 출력

t = (20, 8)
divmod(*t)
# * :언패킹할 변수를 가지고 있을 떄 사용 함(병렬 할당)

quotient,remainder = divmod(*t)
quotient, remainder

(2, 4)

In [25]:
#예제14
import os
_,filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
#_(placeholder): 필요없는 값 저장
filename

'idrsa.pub'

In [24]:
#예제15
a, b, *rest = range(5)
a, b, rest
#a,b까지는 보통 할당, *rest에 초과된 인수를 할당해줌(가변길이 변수 받아오기)
#리스트 형태로 받아옴

a, b, *rest = range(3)
a, b, rest

a, b, *rest = range(2)
a, b, rest
#들어올 값이 없으면 공백리스트가 됨

(0, 1, [])

In [26]:
#예제16
a, *body, c, d = range(5)
a, body, c, d
#중간 사용시 초과될 인수만큼 알아서 할당되어 리스트로 받아짐
#(0, [1, 2], 3, 4)

*head, b, c, d = range(5)
head, b, c, d

([0, 1], 2, 3, 4)

In [27]:
#예제17
metro_areas = [
      ("Tokyo", "JP", 36.933, (35, 139)),
      ("Delhi NCR", "IN", 21, (28,77)),
      ("Mexico City", "MX", 20, (19, -99)),
      ("New York-Newark", "US", 20, (40, -74)),
      ("Sao Paulo", "BR", 19, (-23, -46))
]
print("{:15} | {:^9} | {:^9}".format('', 'lat.', 'long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'

for name, cc, pop, (lat, longi) in metro_areas:
    if longi <= 0:
        print(fmt.format(name, lat, longi))

                |   lat.    |   long.  
Mexico City     |   19.0000 |  -99.0000
New York-Newark |   40.0000 |  -74.0000
Sao Paulo       |  -23.0000 |  -46.0000


###네임드 튜플

In [29]:
#예제18
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
#레코드 필드의 이름
tokyo = City('Tokyo','JP', 36.933, (35.689, 139.691))
#어싸인된 변수에 값 추가
tokyo
tokyo.population
tokyo.coordinates
tokyo[1]

'JP'

In [35]:
#예제19
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo','JP', 36.933, (35.689, 139.691))

City._fields
#('name', 'country', 'population', 'coordinates')

LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613, 77.208))
delhi = City._make(delhi_data)
delhi._asdict()
# {'name': 'Delhi NCR',
# 'country': 'IN',
# 'population': 21.935,
# 'coordinates': LatLong(lat=28.613, long=77.208)}


for key, value in delhi._asdict().items():
    print(key + ':', value)

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613, long=77.208)


In [40]:
#예제20
ㅣ = [10, 20, 30, 40, 50, 60]
ㅣ[:2]
#[10, 20]
ㅣ[2:]
#30, 40, 50, 60]
ㅣ[:3]
#[10, 20, 30]
ㅣ[3:]
#[40, 50, 60]

[40, 50, 60]

In [51]:
#예제21
invoice = """
  0.....6..................25........33......40.......
  1909 Pimoroni             $17.50    3      $52.50
  1489 6mm Tactile          $4.95     2      $9.90
  """

SKU = slice(0,6)
DESCRIPTION = slice(6,25)
UNIT_PRICE = slice(25,33)
QUANTITTY = slice(33,40)
ITEM_TOTAL = slice(40, None)

line_items = invoice.split('\n')[2:]

for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])

   $17.5  Pimoroni          
   $4.95  6mm Tactile       
 


In [57]:
#예제22
l = list(range(10))
l
#0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
l[2:5] = [20,30]
l
#[0, 1, 20, 30, 5, 6, 7, 8, 9]
del l[5:7]
l
#0, 1, 20, 30, 5, 8, 9]
l[3::2] = [11, 22]
l
#[0, 1, 20, 11, 5, 22, 9]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [60]:
#예제23
l[2:5] = 100

TypeError: can only assign an iterable

In [58]:
#예제24
l[2:5] = [100]
l

[0, 1, 100, 5, 6, 7, 8, 9]

In [62]:
#예제25
ㅣ = [1,2,3]
ㅣ*5
#1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3
5* 'abcd'

'abcdabcdabcdabcdabcd'

In [64]:
#예제26
board = [['_'] * 3 for i in range(3)]
board
#['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

board[1][2] = 'X'
board


[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [66]:
#예제27
weird_board = [['_'] * 3] * 3
weird_board
#[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

weird_board[1][2] = '0'
weird_board

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

In [67]:
#예제28
row = ['_'] * 3
board = []
for i in range(3):
    board.append(row)

board[1][2] = 'X'

board

[['_', '_', 'X'], ['_', '_', 'X'], ['_', '_', 'X']]

In [68]:
#예제29
board = []
for i in range(3):
    row = ['_'] * 3
    board.append(row)

print(board)

board[2][0] = 'X'

board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]


[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]

In [71]:
#예제30
l = [1,2,3]
id(l)
#136741632157888

l *= 2
l
#[1, 2, 3, 1, 2, 3]

id(l)

136741656476288

In [73]:
#예제31
t = (1,2,3)
id(t)
#136741633024768

t *= 2
id(t)

136741642133248

In [ ]:
#예제32
t = (1,2, [30,40])
print(t)

t[2] += [50,60]

In [78]:
#예제33
t = (1,2, [30,40])
print(t)

t[2] += [50 ,60]

(1, 2, [30, 40])


TypeError: 'tuple' object does not support item assignment

In [82]:
#예제34
fruits = ['grape','raspberry','apple','banana']
sorted(fruits)
#['apple', 'banana', 'grape', 'raspberry']

fruits
#['grape', 'raspberry', 'apple', 'banana']

sorted(fruits, reverse=True)
#['raspberry', 'grape', 'banana', 'apple']

sorted(fruits, key=len)
#key=len: 요소의 길이별로 정렬

['frape', 'apple', 'banana', 'raspberry']

In [85]:
#예제35
fruits = ['grape','raspberry','apple','banana']
sorted(fruits, key=len, reverse=True)
#['raspberry', 'banana', 'grape', 'apple']

fruits
#['frape', 'raspberry', 'apple', 'banana']

fruits.sort()
fruits

['apple', 'banana', 'grape', 'raspberry']

In [87]:
#예제36
from array import array
from random import random

floats = array('d', (random() for _ in range(10**7)))
floats[-1]

0.4062686287327043

In [91]:
#예제37
with open('floats.bin', 'wb') as f:
    floats.tofile(f)

floats2 = array('d')

with open('floats.bin', 'rb') as f:
      floats2.fromfile(f, 10**7)

floats2[-1]
#0.4062686287327043
floats == floats2

True

In [96]:
#예제38
import array
numbers = array.array('h', [-2,-1,0,1,2])
memv = memoryview(numbers)
len(memv)
#5

memv[0]
#-2

memv_oct = memv.cast('B')
memv_oct.tolist()
#[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

In [98]:
#예제39
import numpy
a = numpy.arange(12)
a
#array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

type(a)

numpy.ndarray

In [100]:
#예제40
import numpy
a = numpy.arange(12)

a.shape
#(12,)

a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
#예제41
import numpy
a = numpy.arange(12)
a.shape = 3, 4

a[2]
#array([ 8,  9, 10, 11])

a[2,1]
#9

a[:, 1]
#array([1, 5, 9])

array([1, 5, 9])

In [104]:
#예제42
import numpy
a = numpy.arange(12)
a.shape = 3, 4

a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
#예제43
from collections import deque
dq = deque(range(10), maxlen = 10)
dq
#eque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

dq.rotate(3)
dq
#deque([74, 5, 6, 7, 8, 9, 0, 1, 2, 3])

dq.rotate(-4)
dq
#deque([8, 9, 0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
#예제44
from collections import deque
dq = deque(range(10), maxlen = 10)

dq.appendleft(-1)
dq
#deque([-1, 8, 9, 0, 1, 2, 3, 4, 5, 6])

dq.extend([11, 22, 33])
dq
#deque([0, 1, 2, 3, 4, 5 , 6, 11, 22, 33])

dq.extendleft([10, 20, 30, 40])
dq
#deque([40, 30, 20, 10, 0, 1, 2, 3, 4, 5])